import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {products} from './data/products';
import './styles.css';

const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' F CFA';
const CART='nightdrop-cart', DEADLINE='nightdrop-deadline';
function getDeadline(){const s=Number(localStorage.getItem(DEADLINE));if(s&&s>Date.now())return s;const d=Date.now()+((5*24+5)*60*60*1000)+(42*60*1000)+18000;localStorage.setItem(DEADLINE,d);return d;}

function App(){
 const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem(CART)||'[]'));
 const [drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[confirmed,setConfirmed]=useState(false);
 const [deadline]=useState(getDeadline),[form,setForm]=useState({name:'',phone:'',address:''});
 const [time,setTime]=useState({days:5,hours:5,minutes:42,seconds:18});
 useEffect(()=>localStorage.setItem(CART,JSON.stringify(cart)),[cart]);
 useEffect(()=>{const f=()=>{let r=Math.max(0,deadline-Date.now()),s=Math.floor(r/1000);setTime({days:Math.floor(s/86400),hours:Math.floor(s/3600)%24,minutes:Math.floor(s/60)%60,seconds:s%60})};f();const t=setInterval(f,1000);return()=>clearInterval(t)},[deadline]);
 const items=useMemo(()=>cart.map(i=>({...i,product:products.find(p=>p.id===i.id)})),[cart]);
 const count=cart.reduce((a,i)=>a+i.qty,0), subtotal=items.reduce((a,i)=>a+i.product.price*i.qty,0);
 const scroll=()=>document.getElementById('products')?.scrollIntoView({behavior:'smooth'});
 const add=id=>{setCart(c=>{const x=c.find(i=>i.id===id);return x?c.map(i=>i.id===id?{...i,qty:Math.min(i.qty+1,products.find(p=>p.id===id).stock)}:i):[...c,{id,qty:1}]});setDrawer(true)};
 const qty=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(0,Math.min(i.qty+d,products.find(p=>p.id===id).stock))}:i).filter(i=>i.qty));
 const confirm=e=>{e.preventDefault();setCheckout(false);setConfirmed(true);setCart([])};
 const whatsapp=()=>{const text=encodeURIComponent('Bonjour NightDrop, je souhaite commander : '+items.map(i=>`${i.product.name} x${i.qty}`).join(', ')+`. Total : ${money(subtotal)}.`);window.open('https://wa.me/22900000000?text='+text,'_blank','noopener,noreferrer')};
 return <div className="shell">
  <header className="nav"><a className="brand" href="#top"><span className="mark">N</span><span><b>NIGHTDROP</b><small>HALLOWEEN MARKET</small></span></a><nav><a href="#offers">Offres</a><a href="#reviews">Avis</a><a href="#about">Pourquoi nous</a></nav><button className="cart" onClick={()=>setDrawer(true)}>Panier <span>{count}</span></button></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><span className="eyebrow">HALLOWEEN • OFFRES LIMITÉES</span><h1>La nuit des <span>offres qui font peur.</span></h1><p>Des produits sélectionnés pour Halloween avec jusqu’à <b>−50 %</b>. Profitez de la promo avant la fin du compte à rebours.</p><div className="actions"><button className="primary" onClick={scroll}>J’en profite à −50 %</button><button className="secondary" onClick={scroll}>Voir les offres</button></div><div className="trust"><span>✓ Commande simple</span><span>✓ Paiement démo sécurisé</span><span>✓ Support WhatsApp</span></div></div><div className="hero-art"><div className="moon"/><div className="ghost">👻</div><div className="pumpkin">🎃</div><div className="sale"><span>FLASH SALE</span><b>−50 %</b><small>sur une sélection</small></div></div></section>
   <section className="countdown"><div><span className="kicker">L’OFFRE SE TERMINE DANS</span><h2>Le temps presse.</h2></div><div className="timer">{[['days','Jours'],['hours','Heures'],['minutes','Min'],['seconds','Sec']].map(([k,l])=><div key={k}><b>{String(time[k]).padStart(2,'0')}</b><small>{l}</small></div>)}</div></section>
   <section className="section" id="products"><div className="section-head" id="offers"><div><span className="kicker">SÉLECTION HALLOWEEN</span><h2>Les offres qui partent vite</h2></div><p>Stocks limités pendant la campagne.</p></div><div className="grid">{products.map(p=><article className="card" key={p.id}><div className="product-art"><span className="badge">{p.badge}</span><div>{p.icon}</div></div><div className="content"><div className="rating">★★★★★ <span>{p.rating}</span></div><small className="cat">{p.category}</small><h3>{p.name}</h3><div className="prices"><s>{money(p.oldPrice)}</s><b>{money(p.price)}</b></div><small className="stock">Plus que {p.stock} en stock</small><button className="buy" onClick={()=>add(p.id)}>Acheter maintenant</button></div></article>)}</div></section>
   <section className="benefits" id="about"><article><span>01</span><h3>Une offre claire</h3><p>Prix, réduction et disponibilité immédiatement visibles.</p></article><article><span>02</span><h3>Mobile d’abord</h3><p>Une expérience conçue pour le téléphone.</p></article><article><span>03</span><h3>Commande simple</h3><p>Produit → panier → formulaire → confirmation.</p></article></section>
   <section className="section" id="reviews"><div className="section-head"><div><span className="kicker">AVIS CLIENTS</span><h2>Ils ont déjà craqué.</h2></div></div><div className="reviews"><article><div className="stars">★★★★★</div><p>“Le site est super clair et la promo est impossible à rater.”</p><b>Aïcha M.</b><small>Cliente vérifiée</small></article><article><div className="stars">★★★★★</div><p>“J’ai trouvé le pack que je cherchais immédiatement.”</p><b>David K.</b><small>Client vérifié</small></article><article><div className="stars">★★★★★</div><p>“Les produits et les réductions sont très faciles à comprendre.”</p><b>Naïma S.</b><small>Cliente vérifiée</small></article></div></section>
   <section className="final"><div><span className="kicker">DERNIÈRE CHANCE</span><h2>Prêt à faire votre panier Halloween ?</h2><p>Les offres restent disponibles jusqu’à la fin du compte à rebours.</p></div><button className="primary" onClick={scroll}>Voir les produits</button></section>
  </main>
  <footer><div><b>NIGHTDROP</b><p>Halloween Market · Démo front-end</p></div><p>© 2026 NightDrop. Tous droits réservés.</p></footer>
  {drawer&&<div className="overlay" onMouseDown={()=>setDrawer(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="kicker">VOTRE SÉLECTION</span><h2>Panier</h2></div><button className="close" onClick={()=>setDrawer(false)}>×</button></div>{!items.length?<div className="empty"><div>🕸️</div><h3>Votre panier est vide.</h3><p>Ajoutez un produit pour commencer votre commande.</p><button className="primary" onClick={()=>{setDrawer(false);scroll()}}>Découvrir les offres</button></div>:<><div className="cart-list">{items.map(({product,qty:q})=><div className="cart-item" key={product.id}><div className="mini">{product.icon}</div><div><b>{product.name}</b><span>{money(product.price)}</span><div className="qty"><button onClick={()=>qty(product.id,-1)}>−</button><em>{q}</em><button onClick={()=>qty(product.id,1)}>+</button></div></div><button className="remove" onClick={()=>setCart(c=>c.filter(i=>i.id!==product.id))}>Supprimer</button></div>)}</div><div className="summary"><div><span>Sous-total</span><b>{money(subtotal)}</b></div><small>Paiement réel non activé : démonstration front-end.</small></div><button className="primary full" onClick={()=>{setDrawer(false);setCheckout(true)}}>Passer la commande</button><button className="secondary full" onClick={whatsapp}>Commander via WhatsApp</button></>}</aside></div>}
  {checkout&&<div className="overlay" onMouseDown={()=>setCheckout(false)}><section className="checkout" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="kicker">CHECKOUT</span><h2>Finaliser la commande</h2></div><button className="close" onClick={()=>setCheckout(false)}>×</button></div><form onSubmit={confirm}><label>Nom complet<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. Samah Joevanix"/></label><label>Téléphone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Ex. +229 97 00 00 00"/></label><label>Adresse<textarea required rows="3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Ville, quartier..."/></label><div className="payment"><b>Paiement sécurisé — démonstration</b><span>Mobile Money · Visa · Mastercard</span></div><button className="primary full" type="submit">Confirmer la commande — {money(subtotal)}</button></form></section></div>}
  {confirmed&&<div className="success"><div><span>✓</span><div><b>Commande confirmée</b><p>Votre commande est confirmée dans cette démo front-end.</p></div></div><button className="close" onClick={()=>setConfirmed(false)}>×</button></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
